In [1]:
import numpy as np

In [31]:
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [6]:
import pandas as pd

In [13]:
# data = pd.read_csv('movie.csv')
data = pd.read_csv("/mnt/c/Users/ssait/Downloads/movie.csv")
# "C:\Users\ssait\Downloads\movie.csv"


In [15]:
data.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0


In [19]:
data.columns

Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='str')

In [23]:
new_df = data.iloc[:, 3:]

In [29]:
genres = new_df.columns